# Change these first
owner: ANONSENSEBOT # Your GitHub organization or username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Cinte's Blog
    url: https://blog.cinte.cc
  - name: RSSHUB
    url: https://rsshub.cinte.cc
  - name: FFXIVBOT for Migang
    url: https://bot.cinte.cc
  - name: Migang Image Bed
    url: https://image.cinte.cc
  - name: 闪耀暖暖API
    url: https://api.sunuannuan.com/api/assets?category=nikki

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.cinte.cc
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "cinte's severs uptime page"
  introMessage: cinte's server status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
